import React, { Suspense } from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls, useGLTF } from '@react-three/drei';

function ArchitecturalModel({ url }: { url: string }) {
  // Declaratively load the GLTF model generated by the cloud pipeline
  const { scene } = useGLTF(url);
  return <primitive object={scene} />;
}

export default function FloorplanViewer({ url = "https://storage.googleapis.com/your-bucket/scan_0042.gltf" }: { url?: string }) {
  return (
    <div style={{ width: '100%', height: '100%', minHeight: '400px' }} className="rounded-xl overflow-hidden bg-slate-900 relative">
      <Canvas data-testid="r3f-canvas" camera={{ position: [0, 5, 10], fov: 50 }}>
        <ambientLight intensity={0.5} />
        <directionalLight position={[10, 10, 5]} intensity={1} />
        <Suspense fallback={null}>
            <ArchitecturalModel url={url} />
        </Suspense>
        <OrbitControls makeDefault />
      </Canvas>
      <div className="absolute bottom-4 left-4 right-4 text-center pointer-events-none">
        <span className="bg-black/50 text-white text-xs px-3 py-1 rounded-full backdrop-blur-md">
          Drag to rotate • Scroll to zoom
        </span>
      </div>
    </div>
  );
}
